const ACTION_TYPES = {
  COUNTER_INCREMENT: 'COUNTER_INCREMENT',
  COUNTER_DECREMENT: 'COUNTER_DECREMENT',
  COUNTER_SET_STEP: 'COUNTER_SET_STEP',

  ADD_TASK_ACTION: 'ADD_TASK_ACTION',
  UPDATE_TASK_ACTION: 'UPDATE_TASK_ACTION',
  REMOVE_TASK_ACTION: 'REMOVE_TASK_ACTION',
};

export default ACTION_TYPES;
